SJTU-CSE/awesome-cs

README.md

Add items in CS158, MS125, CS241, CS356.

Add Galaxies' work.

---

README.md

I've updated my work on CS158 and CS356.

Update Bugen's work

---

README.md

course: reorder items

---

README.md

course: CS125 程序设计

---

README.md

docs: ready for transferring to SJTU-CSE

---

README.md

course: add CS241 by @xavihart

---

README.md

course: add CS214 by LuminousXLB

---

README.md

course: add CS356 project by xavihart

---

README.md

add one item to CS214 - 算法与复杂性 (@Flash-321)
**请确认以下事项**

course: add CS214 and CS499 by Flash-321

---

README.md

**请确认以下事项**
由于 GitHub 的新 UI 在显著位置显示了所有 Contributor，故去除这个 badge。

docs: remove contributor badge

---

README.md

Add CS214 Projects

---

README.md

course: change order of CS214

---

README.md

notes: add EI209 and CS307 by Flash-321

---

.github/workflows/greetings.yml

ci: add greetings for first PR

---

.github/workflows/check_url.yml
README.md
parser.py
tests/Fail.md
url_check.sh

ci: more test cases and better code style

---

README.md

course: add CS356 project 2 by skyzh

---

README.md

add CS356 by Flash-321
**请确认以下事项**

course: add CS356 by Flash-321

---

README.md

course: add CS356 project 2 by ClearloveWei

---

README.md

course: add CS356 by KoalaYan

---

README.md

notes: add notes of CS214, CS307, CS359, CS499, EI209

---

README.md

course: add CS356 project 2 by BugenZhao

---

README.md

course: add entry of CS145

---

README.md

notes: add notes of CS358, CS214, CS308 by Neight99.
course: add entry of CS308.
**请确认以下事项**

course, notes: add CS358, CS214, CS308 by Neight99

---

README.md

notes: add CS307, CS359, EI209 by skyzh

---

README.md

course: update CS358

---

.github/workflows/check_url.yml
parser.py
tests/Fail.md

failure-cs output:
```
*    [CS200: 失败学课程设计](#cs000) should fail ❌ failed to parse: unmatched course id and anchor
*    [CS200: 失败学课程设计](#cs200) should pass  ✅ 
*    [CS201, CS202, CS203: 失败学导论](#cs201) should pass  ✅ 
*    [CS233: 失败学导论](#cs233) should pass  ✅ 
*    [CS200](#cs233) should fail ❌ failed to parse: no [ID, course name](#anchor) found
*    [CS234: 失败学综合实践](#cs234) should pass  ✅ 
*    [CS200: 失败学课程设计](#cs200) should fail ❌ course ID not in sequence
*    [cs200: 失败学课程设计](#cs200) should fail ❌ failed to parse: please use upper case in course ID
*    [CS200: 失败学课程设计](#CS200) should fail ❌ failed to parse: please use lower case in URL anchor
*    [CS235: 失败学毕业设计](#cs235) should pass  ✅ 
<a name="cs233"></a>
❌ missing item: [('CS200', '失败学课程设计'), ('CS201', '失败学导论')]
*    如何做一个失败者 …
```

ci: support TOC check

---

README.md

**请确认以下事项**
Maintainer's note:
* 合并该 PR 需要 @wzh99 的许可。
* 在合并时请使用以下信息作为 commit body，以表明项目所有者。
```
Co-Authored-By: wzh99 <wzh1999_frog@126.com>
```
---
学长你好 @wzh99 ！最近我们看到您的 GitHub 主页下有许多计算机系课程相关的项目。我们觉得这些项目很有参考价值，因此希望可以将它们加入到计算机系大作业参考的列表中。如果您同意的话，请在这个 PR 下回复“同意”，或者通过 Review 功能同意这个 PR。我们会进行后续的合并操作。感谢。

course: add projects by wzh99

---

README.md

**请确认以下事项**
* 合并该 PR 需要 @Youngzt998 的许可。
* 在合并时请使用以下信息作为 commit body，以表明项目所有者。
```
Co-Authored-By: Ziteng Yang <youngster@sjtu.edu.cn>
```
---
学长你好 @Youngzt998 ！最近我们看到您的 GitHub 主页下有许多计算机系课程相关的项目。我们觉得这些项目很有参考价值，因此希望可以将它们加入到计算机系大作业参考的列表中。如果您同意的话，请在这个 PR 下回复“同意”，或者通过 Review 功能同意这个 PR。我们会进行后续的合并操作。感谢。

course: add CS149, CS339, CS383 by Youngzt998

---

README.md

**请确认以下事项**
* 合并该 PR 需要 @Vic0428 的许可。
* 在合并时请使用以下信息作为 commit body，以表明项目所有者。
```
Co-Authored-By: Weiqi Feng <fengweiqi@sjtu.edu.cn>
```
---
学长你好 @Vic0428 ！最近我们看到您的 GitHub 主页下有操作系统课程相关的项目。我们觉得这个项目很有参考价值，因此希望可以将它加入到计算机系大作业参考的列表中。如果您同意的话，请在这个 PR 下回复“同意”，或者通过 [Review](https://github.com/SJTU-CSE/awesome-cs/pull/50/files) 功能同意这个 PR。我们会进行后续的合并操作。感谢。

course: add CS356 project by Vic0428

---

README.md

course, notes: add CS356 project and CS499 notes by Youngzt998

---

README.md

course: add CS145 project by skyzh

---

README.md

docs: update contribution guide

---

README.md

**请确认以下事项**
* 合并该 PR 需要 @nexuslrf 的许可。
* 在合并时请使用以下信息作为 commit body，以表明项目所有者。
```
Co-Authored-By: RF Liang <shootingstarlrf@hotmail.com>
```
---
学长你好 @nexuslrf ！最近我们看到您的 GitHub 主页下有操作系统课程相关的项目。我们觉得这个项目很有参考价值，因此希望可以将它加入到计算机系大作业参考的列表中。如果您同意的话，请在这个 PR 下回复“同意”，或者通过 [Review](https://github.com/SJTU-CSE/awesome-cs/pull/55/files) 功能同意这个 PR。（否则，请直接关闭 Pull Request。）我们会进行后续的合并操作。感谢。
btw，看起来您的项目中含有 GPLv2 授权的 Linux 代码。因此，我们建议您在项目中添加一个 GPLv2 许可证。（在 GitHub 网页上 Create New File，输入文件名 LICENSE，选择 GPLv2 即可）

add CS356 project by nexuslrf

---

README.md

add CS145 project by BugenZhao

---

README.md

An OPG (Operator Precedence Grammar) analyzer/parser.
**请确认以下事项**

course: add CS308 project by keithnull

---

README.md

course: add CS145 labs by Galaxies99

---

README.md

course: add CS145, CS356, CS359 by davidwang200099

---

README.md

course: add CS359 project by zztoy

---

README.md

Adding MS125 work: RISC-V Simulator and BASIC Compiler
**请确认以下事项**

course: add MS125 project by Victrid

---

README.md

course: update a link of CS356

---

README.md

course: add CS241, CS307

---

README.md

add CS241 2020 Fall

---

README.md

add IS307, CS386, CS467, SE305 course notes, and CS386 course project
**请确认以下事项**

course, notes: add IS307, CS386, CS467, SE305 by Galaxies99

---

README.md

notes: add CS339 by PeiyuChen1005

---

README.md

course: add CS236, CS410

---

README.md

course: add CS339 project

---

README.md

course: add EE458 projects

---

README.md

docs: remove hit badge

---

README.md

course: add EI209 labs

---

README.md

course: add CS499 material

---

README.md

course: add CS473 homework and project

---

README.md

course: add CS145,CS356,EI209

---

README.md

Fix https://github.com/SJTU-CSE/awesome-cs/issues/81

course: update course name of CS410

---

README.md

添加CS241 问题求解与实践、CS359 计算机系统结构
**请确认以下事项**

add CS359,CS241

---

README.md

course: add CS241 project

---

README.md

course: add CS385, EE359, EE447, EI314 course data

---

README.md

course: add EI314 projects

---

README.md

Add new labs and projects for courses in 2021 Spring

---

README.md

Add labs and notes

---

README.md

course: add CS339 2021 Fall

---

README.md

course: add CS433

---

README.md

add CS236,CS339,CS410

---

README.md

Add CS236, CS467

---

README.md

course: add CS337, CS339, CS410

---

README.md

course: add CS337

---

README.md
parser.py

**请确认以下事项**
Since all course numbers in the Computer Science Department were updated since the class of 2020, I think it is necessary to update the new course numbers for this project. At the same time, the original course numbers have been retained. (I made the changes manually based on the data on [plus.sjtu.edu.cn](https://plus.sjtu.edu.cn/course-plus/), so there may still be errors despite my multiple checks.)
The style-checking script has also been updated.

update course number

---

README.md
parser.py

course: add CS2301, CS3303, CS3312, CS3507

---

README.md

Update DIP project(Depth Estimation) for 2021Fall

---

README.md

course: add CS383 project by PhotonQuantum

---

README.md

add project for course: computer graphics

---

README.md

add: 人工智能2022秋英文班项目（SAT求解器）（最佳性能小组）

---

README.md
parser.py

add CS3322,EE458,EI328

---

README.md

Update CS0501H, CS2303

---

README.md

add CS0501 CS2303

---

README.md

course: add CS4302 project

---

README.md

add CS2305 notes

---

README.md

Add CS2303, CS2308

---

README.md

update CS2302 to CS2310 and add it.

---

README.md

Add CS1956

---

README.md

Update OS and Architecture, 2023 Spring

---

README.md

add CS2308

---

README.md

Update CS2309, CS3317

---

README.md

add CS3308

---

README.md

update CS3333 style

---

README.md

大作业另有一份存于https://github.com/SusieGlitter/puzzle24_LANbattle 且含release
为了保持队形没有列出，仅在https://github.com/SusieGlitter/CS2309-02 的对应文件夹md中指向
**请确认以下事项**

Update README.md about CS-2309 (2024 fall)

---

README.md

Add my work on projects of CS2303 and homework of CS2308
**请确认以下事项**

Update CS2303 CS2308

---

README.md

Add CS2304, 2025Spring

---

README.md

Correct the semester of CS2307 uu-matter543
